### PR TITLE
Spinners store values to SharedPreferences

### LINKED ISSUE #11: Make spinners store values to SharedPreferences
Must start after #10 is solved.

### Expected Behaviour
Selecting options from the dropdown should set a corresponding value to SharedPreferences.
e.g. Choosing 25 minutes from spinner should set a value `150000` (miliseconds) to SharedPreferences.

This problem hasn't been figured out end-to-end and will require some experimenting on your end - but here's a supporting SO [link](https://stackoverflow.com/questions/5068115/spinner-selection-save-to-sharedpreferences-then-retrieve).

Please include `Log.v(` statements for easy testing purposes.

If you hit a dead-end, comment back here with the problem and we'll solve this together.... 

Please declare all miliseconds as a final constant.
e.g.  `private final long TWENTY_FIVE_MINUTES = 150000;`

-----------------------------------

Interested in taking up this issue? Leave a comment expressing you interest along with you `@slack id.abnd`.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

### PR DESCRIPTION
**Pull request by codersanjeev**
## Spinners store values to SharedPreferences

Storing the positions of selected items in SharedPreferences.
Corresponding keys are stored in the strings.xml file.

Fixes #11 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by numerative** [comment]
Hi @thedevelopersanjeev,
Good job deciding to store the location values to sharedpreferences editor. However, before this can be merged, I have got a few suggestions.
1. Please sync your local repo with the upstream so that only one commit is there for the pull request.
2. The initspinner method defaults spinner positions to 1 every time the activity starts. Expected behaviour should be to `setSelection(` to default values when the app is run the first time and consecutively, it should read from sharedPreferences.

**Comment by codersanjeev** [comment]
Fixed both issues @numerative

**Comment by numerative** [comment]
The app is crashing, can you please recheck.
Also, please drop or squash unnecessary commits.

**Comment by codersanjeev** [comment]
App crashing issue fixed @numerative

**Comment by numerative** [comment]
Great stuff! Your changes have been rebased and merged.

Before making any future changes run the following commands on your local repo in order to sync with upsteram.

1. `git fetch upstream/master`
2. `git reset --hard upstream/master`
3. `git push --force origin/master`

Many Thanks! 👍 😄

**Pull request closed without merging**
